---
title: "Congratulations!"
description: "Understanding how to build a user interface"
page-layout: article
sidebar: getstarted-r

lightbox:
  effect: fade
always_allow_html: true
---

You now know how to get started with building web apps in R with Shiny!

### What did you learn?

In this course you have learned:

* How to design a Shiny app from scratch
* The essentials of reactive programming
* You also got practice with customizing your app's UI
* Employing reactivity best practices

We hope you enjoyed the course and that the topics we discussed in this course motivated you to build your first, and second, and third Shiny app!

Once you build your first app, you have a variety of deployment options.

### shinyapps.io

The first is shinyapps.io. This is a server maintained by Posit, that is easy to use, secure, and scalable. It comes with built in metrics and has a free tier available.

### Shiny Server

If you prefer to build your own server you can use Shiny Server, which is free and open source. It runs on premises, moving your computation closer to your data.

### Pro options

Posit also offers a professional option for deploying your apps: Posit Connect. You can find out more about all of these options at https://shiny.posit.com/deploy.

### Congratulations!

What we covered in this course is just the tip of the Shiny iceberg, so we hope you decide to dive deeper to learn more.

We can't wait to see the apps you create online!
