name: Shiny
baseurl: ''
url: https://shiny.rstudio.com
markdown: kramdown
exclude: [Gemfile, Gemfile.lock, deploy-staging, preview-site, shiny-dev-center.Rproj, staging.pem, README.md, vendor, Dockerfile, Jenkinsfile]
permalink: none

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-feed

feed:
  categories:
    - blog
