---
title: Hosting and deployment
description: When it's time to put your Shiny app on the web, you can choose to deploy on your own servers or on our hosting service.
---

:::{.lead}
When it's time to put your Shiny app on the web, you can choose to deploy on your own servers or on our hosting service.
:::

---

<h2>Deploy to the cloud</h2>
### Shinyapps.io
Host your Shiny apps on the web in minutes with Shinyapps.io. It is easy to use, secure, and scalable. No hardware, installation, or annual purchase contract required. Free and paid options available.

<a class="btn btn-outline-dark btn-sm mt-3 no-icon" href="http://www.shinyapps.io/" target="_blank">Learn more</a> 
<a class="btn btn-outline-dark btn-sm mt-3 no-icon" href="https://shiny.posit.co/r/articles/share/shinyapps/" target="_blank">Get started</a> 
<a class="btn btn-outline-dark btn-sm mt-3 no-icon" href="https://support.rstudio.com/hc/en-us/sections/203868087-shinyapps-io" target="_blank">FAQ</a> 

<hr class="my-5">

<h2>Deploy on-premises or in your VPC <br>(open source)</h2>
### Shiny Server
Deploy your Shiny apps and interactive documents on-premises with open source [Shiny Server](https://www.rstudio.com/products/shiny/shiny-server/), which offers features such as multiple apps on a single server and deployment of apps behind firewalls.


<a class="btn btn-outline-dark btn-sm mt-3 no-icon" href="https://www.rstudio.com/products/shiny/shiny-server/" target="_blank">Learn more</a> 

<hr class="my-5"> 

<h2> Deploy on-premises or in your VPC <br>(commercial)</h2>


### Posit Connect

[Posit Connect](https://www.rstudio.com/products/connect/) is our flagship publishing platform for the work your teams create in R. With Posit Connect, you can share Shiny applications, R Markdown reports, dashboards and plots, as well as Python-based content, including Flask, Dash, Streamlit and Bokeh, in one convenient place with push-button publishing from the RStudio IDE. Features include scheduled execution of reports and flexible security policies to bring the power of data science to your entire enterprise.



<a class="btn btn-outline-dark btn-sm mt-3 no-icon" href="https://www.rstudio.com/products/connect/" target="_blank">Learn more</a> <a class="btn btn-outline-dark btn-sm mt-3 no-icon" href="https://support.rstudio.com/hc/en-us/sections/205987508-RStudio-Connect#" target="_blank">FAQ</a> 



:::{.column-screen .bg-blue .my-5 .py-4}

:::{.column-body .bg-blue}

## What About Shiny Server Pro?

For several years, Shiny Server Pro has enabled data science teams to securely share their Shiny applications on a commercially supported platform. However, in response to customer demand to be able to share many other forms of R- and Python-based content (in addition to Shiny applications), a few years ago we introduced a new product: [Posit Connect](https://www.rstudio.com/products/connect/).

Posit Connect is a publishing platform for all the work your teams create in R and Python. It enables you to share Shiny applications, R Markdown reports, dashboards, plots, APIs, and more in one convenient place. It provides push-button publishing from the RStudio IDE, scheduled execution of reports, and flexible security policies to bring the power of data science to your entire enterprise.

Reflecting the maturity of Posit Connect as a product, and in order to focus our engineering efforts on providing the best experience for our customers in deploying all forms of R and Python data products, we are discontinuing sales of Shiny Server Pro to new customers. We will continue to support Shiny Server Pro for existing customers, but we strongly recommend customers consider [Posit Connect](https://www.rstudio.com/products/connect/) .

:::
:::

See <a href="https://www.rstudio.com/products/shiny/shiny-server/">a comparison of Posit's hosting and deployment options for Shiny.</a> If you have any questions about which product is the right fit for you, please email <a href="mailto:sales@posit.co">sales@posit.co</a>.
